/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDFa0ObOpx8fnk7N2cjoF9Q",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0c73c7effff4e0086",
            securityGroupIds: [
                "sg-0379d54d5e39062a1",
                "sg-009e2e74caba6f930"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-0aaa9a16e499cd8d9",
                    availabilityZone: "ap-northeast-1a"
                },
                {
                    subnetId: "subnet-047c169a03cd9b8c4",
                    availabilityZone: "ap-northeast-1c"
                }
            ]
        }
    }
}).schema({
    "todos": a.model({
        id: a.integer().required(),
        title: a.string().required(),
        completed: a.integer(),
        created_at: a.datetime(),
        updated_at: a.datetime()
    }).identifier([
        "id"
    ])
});
